version: '3.9'
services:

  sqldata:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=vV5r9tn0M4@
    ports:
        - "1433:1433"
  web:
    build: .
    environment:
       DbServer: "sqldata"
       DbPort: "1433"
       DbName: "bookdb"
       DbPassword: "vV5r9tn0M4@"
       DbUser: "SA"
    ports: 
      - "8080:80"
    restart: on-failure
    depends_on:
      - sqldata
    links:
      - sqldata
  